02/01/2023 19:32:36|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 19:32:36|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 19:32:40|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:39:27|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 19:39:27|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 19:39:30|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:47:04|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 19:47:05|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 19:47:08|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:52:21|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 19:52:21|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 19:52:25|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:54:41|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 19:54:41|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 19:54:44|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:59:03|ERROR   |root                            |Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 95, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 386, in _make_request\n    self._validate_conn(conn)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1042, in _validate_conn\n    conn.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 358, in connect\n    self.sock = conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 179, in _new_conn\n    raise ConnectTimeoutError(\nurllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fb275e48be0>, \'Connection to api.github.com timed out. (connect timeout=None)\')\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 489, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb275e48be0>, \'Connection to api.github.com timed out. (connect timeout=None)\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 22, in check_releases\n    r = requests.get(url_releases, allow_redirects=True)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 553, in send\n    raise ConnectTimeout(e, request=request)\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb275e48be0>, \'Connection to api.github.com timed out. (connect timeout=None)\'))'|
02/01/2023 20:02:28|ERROR   |root                            |Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 95, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 386, in _make_request\n    self._validate_conn(conn)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1042, in _validate_conn\n    conn.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 358, in connect\n    self.sock = conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 179, in _new_conn\n    raise ConnectTimeoutError(\nurllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f522bbe8b20>, \'Connection to api.github.com timed out. (connect timeout=None)\')\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 489, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f522bbe8b20>, \'Connection to api.github.com timed out. (connect timeout=None)\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 22, in check_releases\n    r = requests.get(url_releases, allow_redirects=True)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 553, in send\n    raise ConnectTimeout(e, request=request)\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f522bbe8b20>, \'Connection to api.github.com timed out. (connect timeout=None)\'))'|
02/01/2023 20:03:33|ERROR   |root                            |Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 95, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    sock.connect(sa)\nOSError: [Errno 101] Network unreachable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 386, in _make_request\n    self._validate_conn(conn)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1042, in _validate_conn\n    conn.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 358, in connect\n    self.sock = conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5229a31cc0>: Failed to establish a new connection: [Errno 101] Network unreachable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 489, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7f5229a31cc0>: Failed to establish a new connection: [Errno 101] Network unreachable\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 22, in check_releases\n    r = requests.get(url_releases, allow_redirects=True)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7f5229a31cc0>: Failed to establish a new connection: [Errno 101] Network unreachable\'))'|
02/01/2023 20:03:37|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 20:06:47|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 20:08:14|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 20:09:18|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 20:10:36|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 20:15:57|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 20:17:27|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 20:25:24|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 20:27:10|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 20:27:10|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 20:39:51|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 20:39:51|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 20:39:51|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 20:39:51|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 20:39:51|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 21:38:47|ERROR   |root                            |Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 95, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 386, in _make_request\n    self._validate_conn(conn)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1042, in _validate_conn\n    conn.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 358, in connect\n    self.sock = conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 179, in _new_conn\n    raise ConnectTimeoutError(\nurllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fa0fc21b6d0>, \'Connection to api.github.com timed out. (connect timeout=None)\')\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 489, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa0fc21b6d0>, \'Connection to api.github.com timed out. (connect timeout=None)\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 22, in check_releases\n    r = requests.get(url_releases, allow_redirects=True)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 553, in send\n    raise ConnectTimeout(e, request=request)\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa0fc21b6d0>, \'Connection to api.github.com timed out. (connect timeout=None)\'))'|
02/01/2023 21:38:51|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 21:38:51|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 21:38:51|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 21:38:51|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 21:38:51|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 22:52:13|WARNING |apscheduler.executors.default   |Run time of job "Sync episodes with Sonarr (trigger: interval[1:00:00], next run at: 2023-01-02 23:38:31 CET)" was missed by 0:13:41.854820|
02/01/2023 23:11:33|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 23:11:33|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 23:11:33|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 23:11:33|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 23:11:33|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 23:26:24|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 23:26:24|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 23:26:24|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 23:26:24|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 23:26:24|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 23:33:52|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 23:33:52|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 23:33:52|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 23:33:52|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 23:33:52|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
